version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_blog_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - blog-network

volumes:
  db_data:

networks:
  blog-network:
